/**
 * Static site chrome — copy that isn't a translation of a domain code (that
 * is `messages.ts`'s job) but also isn't a component-local string literal,
 * which the lint rule in `scripts/check-polish-literals.mjs` forbids
 * everywhere under `src/app` and `src/ui`.
 *
 * `catalogue*` entries are real, functional UI chrome for the category/
 * product pages built on the seeded catalogue — labels and structure, not
 * the product descriptions themselves (those come from the database, seeded
 * in `prisma/seed.ts`, and are their own kind of placeholder — see that
 * file's header comment). `home*` is the homepage's own SEO metadata —
 * technical copy, not the hero/craftsmanship/reviews/FAQ narrative content
 * ARCHITECTURE.md §22 describes, which is still unbuilt (see
 * `src/app/(marketing)/page.tsx`'s header comment for why).
 */

export const SITE = {
  homeSeoTitlePl: 'RYT — meble i akcesoria z grawerem',
  homeSeoDescPl:
    'Meble, biżuteria i wykończenia wnętrz z drewna i gresu, z personalizowanym grawerem.',

  catalogueHomeLinkPl: 'Strona główna',
  catalogueStartingPricePrefixPl: 'od',
  catalogueProductionTimeLabelPl: 'Czas realizacji',
  catalogueProductionTimeUnitPl: 'dni roboczych',
  catalogueDimensionsLabelPl: 'Wymiary',
  catalogueMaterialsLabelPl: 'Dostępne materiały',
  catalogueCareInstructionsLabelPl: 'Pielęgnacja',
  catalogueInstallationInfoLabelPl: 'Informacje o montażu',
  catalogueInstallationVariantsLabelPl: 'Warianty montażu',
  catalogueMaterialNotesLabelPl: 'Ważne informacje',
  catalogueEmptyCategoryPl: 'W tej kategorii nie ma jeszcze żadnych produktów.',
  catalogueCategoryNotFoundPl: 'Nie znaleziono takiej kategorii.',
  catalogueProductNotFoundPl: 'Nie znaleziono takiego produktu.',
  catalogueViewProductPl: 'Zobacz produkt',
  catalogueCategoriesHeadingPl: 'Kategorie',
  cardPersonalizationBadgePl: 'Grawer',

  configuratorHeadingPl: 'Skonfiguruj produkt',
  configuratorStepDesignPl: 'Wzór',
  configuratorStepMaterialPl: 'Materiał',
  configuratorStepSizePl: 'Wymiary',
  configuratorStepThicknessPl: 'Grubość',
  configuratorStepFinishPl: 'Wykończenie',
  configuratorStepInstallationVariantPl: 'Sposób montażu',
  configuratorStepPersonalizationPl: 'Personalizacja',
  configuratorStepCustomUploadPl: 'Twój projekt',
  configuratorStepSummaryPl: 'Podsumowanie',
  configuratorBackPl: 'Wstecz',
  configuratorNextPl: 'Dalej',
  configuratorWidthLabelPl: 'Szerokość (cm)',
  configuratorHeightLabelPl: 'Wysokość (cm)',
  configuratorNoOptionsPl: 'Ta opcja nie jest jeszcze dostępna dla wybranej konfiguracji.',
  configuratorStepBlockedPrefixPl: 'Najpierw uzupełnij krok:',
  configuratorNextBlockedPl: 'Uzupełnij ten krok, aby przejść dalej.',
  configuratorPersonalizationUnavailablePl:
    'Ten produkt nie oferuje jeszcze personalizacji tekstem. Ten krok można pominąć.',
  configuratorPersonalizationLabelPl: 'Tekst do wygrawerowania',
  configuratorFontLabelPl: 'Krój pisma',
  configuratorFontRequiredPl: 'Wybierz krój pisma, aby sprawdzić, czy wpisany tekst może zostać wykonany.',
  configuratorPreviewHeadingPl: 'Podgląd',
  configuratorPreviewEmptyPl: 'Wybierz materiał, aby zobaczyć podgląd.',
  configuratorPreviewCaptionPl:
    'Wizualizacja poglądowa złożona z rzeczywistych zdjęć materiału i wzoru zastępczego — ostateczny wygląd produktu może się różnić.',
  configuratorPriceLabelPl: 'Cena',
  configuratorPriceCalculatingPl: 'Obliczanie ceny…',
  configuratorPriceUnavailablePl: 'Podaj wymiary, aby zobaczyć cenę.',
  configuratorPriceUnavailableGenericPl: 'Cena niedostępna dla tej konfiguracji.',
  configuratorModuleCountLabelPl: 'Liczba elementów',
  configuratorAcknowledgeRequiredPl: 'Potwierdzam, że rozumiem powyższą informację.',
  configuratorBlockedPl: 'Ta konfiguracja nie może zostać wykonana. Zmień wybór powyżej.',
  configuratorAddToCartPl: 'Dodaj do koszyka',
  configuratorSaveChangesPl: 'Zapisz zmiany',
  configuratorAddToCartErrorPl:
    'Nie udało się dodać do koszyka. Sprawdź wybory powyżej i spróbuj ponownie.',
  configuratorProductionDaysLabelPl: 'Czas realizacji',
  configuratorClearedFinishPl:
    'Wybrane wykończenie zostało wyczyszczone, ponieważ nie jest dostępne dla nowo wybranego materiału.',
  configuratorClearedThicknessPl:
    'Wybrana grubość została wyczyszczona, ponieważ nie mieści się w wybranym sposobie montażu.',
  configuratorUploadChooseFilePl: 'Wybierz plik (JPG, PNG, SVG lub PDF)',
  configuratorUploadSubmitPl: 'Prześlij projekt',
  configuratorUploadSubmittingPl: 'Przesyłanie…',
  configuratorUploadSuccessPl: 'Projekt został przesłany.',
  configuratorUploadIpConsentLabelPl: 'Akceptuję powyższe oświadczenie',
  configuratorUploadReplacePl: 'Prześlij inny plik',
  // P9 phase 2 — reusing an already-uploaded design from "Moje wzory" instead of uploading fresh.
  configuratorUploadReuseHeadingPl: 'Masz już zapisany wzór? Możesz go użyć zamiast przesyłać nowy plik.',
  configuratorUploadReuseSelectLabelPl: 'Zapisane wzory',
  configuratorUploadReuseButtonPl: 'Użyj tego wzoru',
  configuratorUploadReuseOrNewPl: 'lub prześlij nowy plik poniżej',
  configuratorUploadReuseSuccessPl: 'Wybrano zapisany wzór.',
  configuratorCustomPriceEstimatePl:
    'Podana cena to wstępny szacunek (materiał, wykończenie, cena bazowa). Ostateczna wycena, uwzględniająca złożoność Twojego projektu, zostanie potwierdzona podczas weryfikacji projektu.',

  // Homepage hero — real claims about how this business actually operates,
  // not generic retail trust-badge copy. No "free shipping"/"money-back
  // guarantee" claims: nothing has confirmed either exists yet.
  heroHeadlinePl: 'Meble i dodatki z grawerem, wykonane na wymiar',
  heroSubcopyPl:
    'Projektujemy i wykonujemy unikalne przedmioty z drewna i gresu — od stołków loftowych po biżuterię — z precyzyjnym grawerem CNC i laserowym.',
  heroCtaPl: 'Zobacz kategorie',

  trustMadeToOrderTitlePl: 'Wykonanie na zamówienie',
  trustMadeToOrderDescPl: 'Każdy produkt wykonujemy indywidualnie',
  trustEngravingTitlePl: 'Personalizacja grawerem',
  trustEngravingDescPl: 'Twój wzór, Twój tekst',
  trustPaymentTitlePl: 'Płatność przelewem',
  trustPaymentDescPl: 'Bezpieczne rozliczenie bankowe',
  trustContactTitlePl: 'Kontakt bezpośredni',
  trustContactDescPl: 'Pytania? Napisz do nas',

  homeProductsHeadingPl: 'Nasze produkty',

  filterMaterialLabelPl: 'Materiał',
  filterAllMaterialsPl: 'Wszystkie materiały',
  filterApplyPl: 'Filtruj',
  sortLabelPl: 'Sortuj',
  sortRelevancePl: 'Domyślnie',
  sortPriceAscPl: 'Cena: od najniższej',
  sortPriceDescPl: 'Cena: od najwyższej',

  searchPlaceholderPl: 'Szukaj produktów…',
  searchButtonLabelPl: 'Szukaj',
  searchResultsHeadingPl: 'Wyniki wyszukiwania',
  searchResultsForPl: 'Wyniki dla',
  searchNoResultsPl: 'Nie znaleziono produktów pasujących do wyszukiwania.',
  searchEmptyQueryPl: 'Wpisz szukaną frazę.',

  cartHeadingPl: 'Koszyk',
  cartEmptyPl: 'Twój koszyk jest pusty.',
  cartContinueShoppingPl: 'Przeglądaj produkty',
  cartQuantityLabelPl: 'Ilość',
  cartUpdateQuantityPl: 'Aktualizuj',
  cartRemovePl: 'Usuń',
  cartDuplicatePl: 'Duplikuj',
  cartEditPl: 'Edytuj',
  cartSubtotalLabelPl: 'Suma',
  cartCheckoutCtaPl: 'Przejdź do zamówienia',
  cartIncompleteNoticePl:
    'Ta konfiguracja nie może już zostać wykonana w tej formie — edytuj ją przed złożeniem zamówienia.',

  checkoutHeadingPl: 'Zamówienie',
  checkoutBuyerSectionHeadingPl: 'Dane zamawiającego',
  checkoutEmailLabelPl: 'E-mail',
  checkoutPhoneLabelPl: 'Telefon (opcjonalnie)',
  checkoutFirstNameLabelPl: 'Imię',
  checkoutLastNameLabelPl: 'Nazwisko',
  checkoutInvoiceSectionHeadingPl: 'Dane do faktury (opcjonalnie)',
  checkoutCompanyNameLabelPl: 'Nazwa firmy',
  checkoutNipLabelPl: 'NIP',
  checkoutAddressSectionHeadingPl: 'Adres dostawy',
  checkoutStreetLabelPl: 'Ulica i numer',
  checkoutPostalCodeLabelPl: 'Kod pocztowy',
  checkoutCityLabelPl: 'Miejscowość',
  checkoutDeliverySectionHeadingPl: 'Sposób dostawy',
  checkoutNoDeliveryMethodsPl: 'Obecnie żadna metoda dostawy nie jest dostępna. Skontaktuj się z nami, aby dokończyć zamówienie.',
  checkoutDeliveryEstimateLabelPl: 'Przewidywany czas dostawy:',
  checkoutDeliveryEstimateUnitPl: 'dni roboczych',
  checkoutDeliveryMethodInvalidPl: 'Wybrana metoda dostawy jest już niedostępna — wybierz inną i spróbuj ponownie.',
  checkoutPaymentMethodInvalidPl: 'Wybrana metoda płatności jest już niedostępna — wybierz inną i spróbuj ponownie.',
  checkoutNoPaymentMethodsPl: 'Obecnie żadna metoda płatności nie jest dostępna. Skontaktuj się z nami, aby dokończyć zamówienie.',
  checkoutPaymentSectionHeadingPl: 'Płatność',
  checkoutPaymentBankTransferPl: 'Przelew bankowy',
  checkoutPaymentContactArrangedPl: 'Ustalę szczegóły indywidualnie',
  checkoutSubtotalLabelPl: 'Suma produktów',
  checkoutShippingLabelPl: 'Dostawa',
  checkoutTermsLabelPl: 'Akceptuję regulamin sklepu.',
  checkoutWithdrawalExemptionTextPl:
    'Przyjmuję do wiadomości, że produkty wykonywane na indywidualne zamówienie, według moich specyfikacji, nie podlegają zwrotowi w ramach 14-dniowego prawa odstąpienia od umowy (art. 38 pkt 3 ustawy z dnia 30 maja 2014 r. o prawach konsumenta).',
  checkoutSubmitPl: 'Złóż zamówienie',
  checkoutEmptyCartRedirectPl: 'Twój koszyk jest pusty — wróć do koszyka, aby dodać produkty.',
  checkoutGenericErrorPl: 'Nie udało się złożyć zamówienia. Sprawdź dane powyżej i spróbuj ponownie.',

  orderConfirmationHeadingPl: 'Zamówienie przyjęte',
  orderItemsHeadingPl: 'Zamówione produkty',
  orderNumberLabelPl: 'Numer zamówienia',
  orderTotalLabelPl: 'Do zapłaty',
  orderBankTransferHeadingPl: 'Dane do przelewu',
  orderBankTransferTitlePl: 'Tytuł przelewu',
  orderBankTransferAccountLabelPl: 'Numer konta',
  orderBankTransferAccountPendingPl:
    'Numer konta do przelewu prześlemy osobno — e-mailem lub podczas kontaktu. Nie zawiera go to potwierdzenie.',
  orderContactArrangedNoticePl: 'Skontaktujemy się, aby ustalić szczegóły zamówienia.',
  orderShipmentHeadingPl: 'Wysyłka',
  orderShipmentStatusLabelPl: 'Status',
  orderShipmentCarrierLabelPl: 'Przewoźnik',
  orderShipmentTrackingNumberLabelPl: 'Numer przesyłki',
  orderShipmentShippedAtLabelPl: 'Data nadania',
  orderShipmentEstimatedDeliveryLabelPl: 'Przewidywana data dostawy',
  orderShipmentDeliveredAtLabelPl: 'Data dostarczenia',
  orderShipmentIssueLabelPl: 'Zgłoszony problem',
  orderShipmentManualNoticePl:
    'Status przesyłki jest aktualizowany ręcznie przez nasz zespół, a nie pobierany automatycznie od przewoźnika — może nie odzwierciedlać zmian z ostatnich godzin.',
  orderShipmentNotYetPreparedPl: 'Paczka nie została jeszcze przygotowana do wysyłki.',
  orderEmailFollowUpNoticePl: 'Potwierdzenie zamówienia zostanie przesłane e-mailem.',
  orderNotFoundPl: 'Nie znaleziono takiego zamówienia.',
  orderLookupHeadingPl: 'Sprawdź status zamówienia',
  orderLookupOrderNumberLabelPl: 'Numer zamówienia',
  orderLookupTokenLabelPl: 'Kod dostępu (z potwierdzenia zamówienia)',
  orderLookupSubmitPl: 'Sprawdź',

  footerCategoriesHeadingPl: 'Kategorie',
  footerInfoHeadingPl: 'Informacje',
  footerSearchLinkPl: 'Szukaj produktów',
  footerTermsLinkPl: 'Regulamin',
  footerPrivacyLinkPl: 'Polityka prywatności',
  footerCopyrightPl: 'RYT',
  footerTaglinePl: 'Precyzja CNC. Ciepło rzemiosła.',
  footerBlogLinkPl: 'Blog',
  footerPatternsLinkPl: 'Wzory',
  footerCollectionsLinkPl: 'Kolekcje',

  legalTermsHeadingPl: 'Regulamin',
  legalPrivacyHeadingPl: 'Polityka prywatności',

  headerAccountLinkPl: 'Moje konto',
  headerLoginLinkPl: 'Zaloguj się',
  headerLogoutPl: 'Wyloguj się',

  authLoginHeadingPl: 'Logowanie',
  authRegisterHeadingPl: 'Rejestracja',
  authEmailLabelPl: 'Adres e-mail',
  authPasswordLabelPl: 'Hasło',
  authNameLabelPl: 'Imię i nazwisko',
  authLoginSubmitPl: 'Zaloguj się',
  authRegisterSubmitPl: 'Załóż konto',
  authNoAccountPl: 'Nie masz jeszcze konta?',
  authSwitchToRegisterPl: 'Zarejestruj się',
  authHaveAccountPl: 'Masz już konto?',
  authSwitchToLoginPl: 'Zaloguj się',
  authOrDividerPl: 'lub',
  authOtpRequestSubmitPl: 'Wyślij kod logowania e-mailem',
  authOtpCodeLabelPl: 'Kod logowania',
  authOtpSubmitPl: 'Zaloguj kodem',
  authOtpSentNoticePl: 'Wysłaliśmy kod logowania na podany adres e-mail. Sprawdź skrzynkę.',
  authGenericErrorPl: 'Coś poszło nie tak. Spróbuj ponownie.',

  accountNavOrdersPl: 'Zamówienia',
  accountNavConfigurationsPl: 'Zapisane projekty',
  accountNavDesignsPl: 'Moje wzory',
  accountOrdersHeadingPl: 'Moje zamówienia',
  accountOrdersEmptyPl: 'Nie masz jeszcze żadnych zamówień.',
  accountOrdersEmptyActionPl: 'Przejdź do sklepu',
  accountConfigurationsHeadingPl: 'Moje zapisane projekty',
  accountConfigurationsEmptyPl: 'Nie masz jeszcze żadnych zapisanych konfiguracji.',
  accountConfigurationsEmptyActionPl: 'Skonfiguruj produkt',

  // P9 phase 2 — the standalone "moje wzory" upload/reuse library, moved
  // out of being tied to any one product's configurator flow.
  accountDesignsHeadingPl: 'Moje wzory',
  accountDesignsIntroPl:
    'Tutaj znajdziesz wszystkie pliki, które kiedykolwiek przesłałeś/przesłałaś jako własny projekt. Możesz przesłać nowy wzór lub użyć zapisanego podczas konfigurowania dowolnego produktu, który to umożliwia.',
  accountDesignsEmptyPl: 'Nie masz jeszcze żadnych przesłanych wzorów.',
  accountDesignsUploadHeadingPl: 'Prześlij nowy wzór',
  accountDesignsTitleFieldLabelPl: 'Nazwa wzoru (opcjonalnie)',
  accountDesignsTitleFieldPlaceholderPl: 'np. Logo firmy',
  accountDesignsUploadedAtLabelPl: 'Przesłano',
  accountDesignsUntitledPl: 'Bez nazwy',
  accountConfigurationEditPl: 'Edytuj',
  accountConfigurationAddToCartPl: 'Dodaj do koszyka',

  consentBannerTextPl:
    'Używamy niezbędnych plików cookie do działania koszyka i logowania oraz — za Twoją zgodą — plików analitycznych, które pomagają nam ulepszać sklep.',
  consentBannerAcceptPl: 'Akceptuję',
  consentBannerDeclinePl: 'Tylko niezbędne',

  routeLoadingPl: 'Ładowanie…',

  errorPageHeadingPl: 'Coś poszło nie tak',
  errorPageBodyPl: 'Wystąpił nieoczekiwany błąd. Spróbuj odświeżyć stronę.',
  errorPageRetryPl: 'Spróbuj ponownie',
  errorPageCorrelationIdLabelPl: 'Numer błędu',

  blogHeadingPl: 'Blog',
  blogSeoTitlePl: 'Blog — RYT',
  blogSeoDescPl: 'Artykuły o rzemiośle, materiałach i personalizacji grawerem.',
  blogEmptyStatePl: 'Wpisy pojawią się tutaj wkrótce.',
  blogPublishedLabelPl: 'Opublikowano',
  blogReadMorePl: 'Czytaj dalej',
  blogPostNotFoundPl: 'Nie znaleziono takiego wpisu.',
  homeBlogHeadingPl: 'Z naszego bloga',
  blogViewAllPl: 'Zobacz wszystkie posty',

  patternsHeadingPl: 'Wzory',
  patternsSeoTitlePl: 'Wzory — RYT',
  patternsSeoDescPl: 'Przeglądaj nasze gotowe wzory do grawerowania CNC, a także zewnętrzne, darmowe źródła wzorów.',
  patternsIntroPl:
    'Poniżej znajdziesz wzory z naszej oferty, które można wybrać przy konfiguracji wybranych produktów. Możesz też przesłać własny projekt — zapisane wzory znajdziesz na koncie w sekcji „Moje wzory”.',
  patternsEmptyPl: 'Wzory pojawią się tutaj wkrótce.',
  patternsExternalHeadingPl: 'Zewnętrzne źródła wzorów',
  patternsExternalIntroPl:
    'To linki do niezależnych, zewnętrznych serwisów z darmowymi wzorami do grawerowania i cięcia CNC. Nie są to nasze materiały — każdy link prowadzi do strony innego dostawcy, gdzie obowiązują jego własne zasady korzystania i licencje.',
  patternsExternalBadgePl: 'zasób zewnętrzny',
  patternsExternalEmptyPl: 'Obecnie nie mamy poleconych zewnętrznych źródeł wzorów.',

  collectionsHeadingPl: 'Kolekcje',
  collectionsSeoTitlePl: 'Kolekcje — RYT',
  collectionsSeoDescPl: 'Gotowe, samodzielnie zaprojektowane kolekcje produktów z grawerem — dostępne od ręki, bez konieczności konfiguracji.',
  collectionsIntroPl:
    'To gotowe, samodzielnie zaprojektowane przez nas zestawienia produktów — nie są tworzone na indywidualne zamówienie klienta. Możesz je po prostu przeglądać i zamawiać, tak jak każdy inny produkt w sklepie.',
  collectionsEmptyPl: 'Kolekcje pojawią się tutaj wkrótce.',
  collectionsBadgePl: 'gotowa kolekcja',
  collectionNotFoundPl: 'Nie znaleziono takiej kolekcji.',
  collectionEmptyProductsPl: 'W tej kolekcji nie ma jeszcze żadnych produktów.',

  faqHeadingPl: 'Najczęściej zadawane pytania',
  faqSeoTitlePl: 'Najczęściej zadawane pytania — RYT',
  faqSeoDescPl: 'Odpowiedzi na najczęstsze pytania o zamówienia, personalizację i realizację.',
  faqEmptyStatePl: 'Pytania pojawią się tutaj wkrótce.',
  homeFaqHeadingPl: 'Najczęściej zadawane pytania',
  faqViewAllPl: 'Zobacz wszystkie pytania',

  staticPageNotFoundPl: 'Nie znaleziono takiej strony.',

  homeReviewsHeadingPl: 'Opinie klientów',
  reviewFormHeadingPl: 'Zostaw opinię',
  reviewFormAuthorNameLabelPl: 'Twoje imię (widoczne publicznie)',
  reviewFormRatingLabelPl: 'Ocena (1–5)',
  reviewFormBodyLabelPl: 'Treść opinii',
  reviewFormSubmitPl: 'Wyślij opinię',
  reviewFormThankYouPl: 'Dziękujemy za opinię! Zostanie opublikowana po weryfikacji.',
  reviewAlreadySubmittedPl: 'Opinia dla tego zamówienia została już przesłana.',
  reviewLinkPl: 'Zostaw opinię o tym zamówieniu',
} as const;
